language: c
os: linux
sudo: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - bison
      - flex
      - libelf-dev
      - dpkg-dev
      - debhelper
      - dkms
      - fakeroot
      - gcc-8
      - gcc-9

env:
  - KVER=5.1 && CC=gcc-8
  - KVER=5.2 && CC=gcc-8
  - KVER=5.3 && CC=gcc-8
  - KVER=5.4 && CC=gcc-9
  - KVER=5.5 && CC=gcc-9
  - KVER=5.6 && CC=gcc-9
  - KVER=master && CC=gcc-9

matrix:
  allow_failures:
    - env: KVER=master
  include:
  - script:
    - dpkg-buildpackage -us -uc
    env: KVER="Debian Package Building"

script:
  - ./scripts/build-against-kernel.sh ${KVER} ${CC}
